package com.example.quanlychitieu.util

object Constant {
    val BASE_URL = "http:/172.16.1.27:5000/api/"

    const val EXTRA_REQUESTCODE_PENDING="EXTRA_REQUESTCODE_PENDING"
    const val EXTRA_TITLE = "EXTRA_TITLE"
    const val EXTRA_DECRIPTION="EXTRA_DECRIPTION"
    const val ACTION_SET_EXACT_ALARM = "ACTION_SET_EXACT_ALARM"
    const val ACTION_SET_REPETITIVE_ALARM_WEEK = "ACTION_SET_REPETITIVE_ALARM_WEEK"
    const val ACTION_SET_REPETITIVE_ALARM_MONTH = "ACTION_SET_REPETITIVE_ALARM_MONTH"
    const val EXTRA_EXACT_ALARM_TIME = " EXTRA_EXACT_ALARM_TIME"
}